### PR TITLE
Migrate library to nullsafety

### PR DESCRIPTION
**Pull request by cek-cek**

### CODE REVIEW

**Comment by excogitatr** [comment]
Waiting for this to be merged @petehouston

**Comment by hyungtaecf** [comment]
Is this repo still active?

**Comment by cek-cek** [comment]
Even if not, for now it still serves the purpose pretty well 😄

**Comment by japborst** [comment]
Hey @petehouston, any news on this one?

**Comment by nilsreichardt** [comment]
@petehouston Any news?

**Comment by joseph-fox** [comment]
Is this repo abandoned by its maintainers?

**Comment by nilsreichardt** [comment]
Hi guys! 👋

It seems so that this library is not maintained anymore. Therefore, I decided to create a fork and my own package. Here are the biggest differences:
| | `flutter-emoji` | `dart-emoji` |
|-|-|-|
| Still maintained? | ❌ | ✅ |
| Null Safety | ❌ | ✅ |
| Pure Dart Package | ❌ | ✅ |
| Updated emojis | ❌ | ✅ |

➡️  https://pub.dev/packages/dart_emoji

**Comment by petehouston** [comment]
Migrated to Null-Safety check. Thanks.

**Pull request closed without merging**
